import { jsPDF } from "jspdf";
import { autoTable } from "jspdf-autotable";
import type { AggregateAuditResult } from "@/lib/audit-engine";

function getHealthLabel(score: number): string {
  if (score >= 85) return "Excellent";
  if (score >= 70) return "Good";
  if (score >= 50) return "Moderate";
  return "Critical";
}

export async function generatePdfReport(result: AggregateAuditResult): Promise<Blob> {
  const doc = new jsPDF({ format: "a4", unit: "mm" });

  // Colors
  const PRIMARY = "#1E40AF";
  const DARK_BG = "#111827";
  const TEXT_SECONDARY = "#6B7280";

  // Header
  doc.setFillColor(17, 24, 39);
  doc.rect(0, 0, 210, 50, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  doc.text("AI Spend Audit Report", 20, 30);

  doc.setFontSize(11);
  doc.setTextColor(156, 163, 175);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`, 20, 42);

  // Executive Summary Card
  doc.setFillColor(31, 41, 55);
  doc.roundedRect(20, 65, 170, 55, 5, 5, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Executive Summary", 30, 80);

  doc.setFontSize(10);
  doc.setTextColor(209, 213, 219);
  doc.setFont("helvetica", "normal");
  const summaryLines = doc.splitTextToSize(result.summary, 150);
  doc.text(summaryLines, 30, 92);

  // Key Metrics
  doc.setFontSize(16);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text("Key Metrics", 20, 145);

  const metrics = [
    ["Metric", "Value"],
    ["Total Current Spend", `$${result.totalCurrentSpend}/mo`],
    ["Optimized Spend", `$${result.totalOptimizedSpend}/mo`],
    ["Monthly Savings", `$${result.totalSavings}/mo`],
    ["Annual Savings", `$${result.totalAnnualSavings}/yr`],
    ["Optimization Score", `${Math.round(result.overallOptimizationScore)}/100`],
    ["Tools Analyzed", String(result.tools.length)],
    ["AI Health Status", getHealthLabel(result.overallOptimizationScore)],
  ];

  autoTable(doc, {
    head: [metrics[0]],
    body: metrics.slice(1),
    startY: 155,
    theme: "grid",
    headStyles: { fillColor: [30, 64, 175], textColor: [255, 255, 255], fontStyle: "bold", fontSize: 10 },
    bodyStyles: { fillColor: [31, 41, 55], textColor: [209, 213, 219], fontSize: 9 },
    alternateRowStyles: { fillColor: [17, 24, 39] },
    tableLineColor: [55, 65, 81],
    tableLineWidth: 0.25,
  });

  const tableEnd = (doc as any).lastAutoTable.finalY + 15;

  // Tool Analysis
  if (tableEnd + 40 < 280) {
    doc.setFontSize(16);
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.text("Tool Analysis", 20, tableEnd);

    const toolRows = result.tools.map((t) => [
      t.tool,
      `$${t.currentSpend}/mo`,
      `$${t.optimizedSpend}/mo`,
      t.savings > 0 ? `$${t.savings}/mo` : "—",
      t.status,
    ]);

    autoTable(doc, {
      head: [["Tool", "Current", "Optimized", "Savings", "Status"]],
      body: toolRows,
      startY: tableEnd + 8,
      theme: "grid",
      headStyles: { fillColor: [30, 64, 175], textColor: [255, 255, 255], fontStyle: "bold", fontSize: 9 },
      bodyStyles: { fillColor: [31, 41, 55], textColor: [209, 213, 219], fontSize: 8 },
      alternateRowStyles: { fillColor: [17, 24, 39] },
      tableLineColor: [55, 65, 81],
      tableLineWidth: 0.25,
    });
  }

  // Recommendations
  const recStart = Math.min((doc as any).lastAutoTable?.finalY ?? tableEnd, 260);
  if (recStart + 30 < 280 && result.priorityRecommendations.length > 0) {
    doc.addPage();
    doc.setFontSize(16);
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.text("Recommendations", 20, 25);

    const recRows = result.priorityRecommendations.map((r, i) => [
      `#${i + 1}`,
      doc.splitTextToSize(r, 120),
    ]);

    autoTable(doc, {
      head: [["#", "Recommendation"]],
      body: recRows,
      startY: 35,
      theme: "grid",
      headStyles: { fillColor: [30, 64, 175], textColor: [255, 255, 255], fontStyle: "bold", fontSize: 9 },
      bodyStyles: { fillColor: [31, 41, 55], textColor: [209, 213, 219], fontSize: 8 },
      alternateRowStyles: { fillColor: [17, 24, 39] },
      tableLineColor: [55, 65, 81],
      tableLineWidth: 0.25,
      columnStyles: { 1: { cellWidth: 140 } },
    });

    // Footer
    const finalY = (doc as any).lastAutoTable?.finalY ?? 250;
    if (finalY < 270) {
      doc.setFontSize(8);
      doc.setTextColor(107, 114, 128);
      doc.text("Generated by AI Spend Audit — Your AI cost optimization platform", 20, 285);
    }
  }

  return doc.output("blob");
}
